subprojects:
  - id: common
    paths:
      - "**"
    checks:
      - "common"
  - id: documentation
    paths:
      - "docs/**"
    checks:
      - "common"
  - id: project_0
    paths:
      - "projects/project_0/**"
    checks:
      - "project_0"
      - "common"
  - id: project_1
    paths:
      - "projects/project_1/**"
    checks:
      - "project_1"
      - "common"
