custom_service_name: "Awesome name that is better than Check Group"
subprojects:
  - id: a-ton-of-checks
    paths:
      - "a-ton-of-checks.md"
    checks:
      - "create-a-ton-of-checks (1)"
      - "create-a-ton-of-checks (60)"
  - id: common
    paths:
      - "**"
    checks:
      - "common"
  - id: invalid
    paths:
      - "**"
    checks:
  - id: documentation
    paths:
      - "docs/**"
    checks:
      - "common"
  - id: project_0
    paths:
      - "projects/project_0/**"
    checks:
      - "project_0"
      - "common"
  - id: project_1
    paths:
      - "projects/project_1/**"
    checks:
      - "project_1"
      - "common"
  - id: project_2
    paths:
      - "projects/project_2/**"
    checks:
      - "project_2_which_does_not_exist"
      - "common"
