name: A Ton of Checks
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "a-ton-of-checks.md"
  push:
    branches:
      - "master"
    paths:
      - "a-ton-of-checks.md"
permissions: write-all
jobs:
  create-a-ton-of-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Check user permission
        id: checks
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./scripts/create-a-ton-of-checks.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
