name: A Ton of Checks
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "a-ton-of-checks.md"
  push:
    branches:
      - "master"
    paths:
      - "a-ton-of-checks.md"
jobs:
  create-a-ton-of-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - run: ./scripts/create-a-ton-of-checks.sh
