name: Common check
on: pull_request
jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: wait
        run: sleep 5
      - name: test
        run: echo "I am common check and I will always succeed."
