name: Project 0
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "projects/project_0/**"
jobs:
  project_0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: echo "I am project 0 and I will always succeed."