name: Project 1
on:
  push:
    paths:
      - "projects/project_1/**"
jobs:
  project_0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "I am project 0 and I will always fail."
          exit 1